name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 11 using Adoptium (or Amazon Corretto)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Use 'adoptium' or 'corretto' as required

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 4: Upload the built artifact (adjust path as needed)
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact  # Name of the artifact
        path: target/*.jar  # Ensure this matches where your JAR is located
