name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (if your project is Java-based)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Change to your Java version if needed
        distribution: 'adoptopenjdk'

    # Step 3: Build the project using Maven (or any build tool you use)
    - name: Build with Maven
      run: mvn clean install

    # Step 4: Upload the built artifact to GitHub Actions Artifacts storage
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact  # Name of the artifact you want to upload
        path: target/*.jar  # Path to the built artifact (adjust to your project build output)
